Repository redhat-developer/helm, pull requests merged in 2019-12, with the labels that each got.

#19 Fix missing virtualenv package in the root image.
  openshift-ci/Dockerfile.tests
Labels: size/XS

#20 Set GOCACHE env variable in the Dockerfile.tests
  openshift-ci/Dockerfile.tests
Labels: size/XS

#21 Create GOCACHE directory.
  openshift-ci/Dockerfile.tests
Labels: size/XS

#22 Set go+w ACLs on GOCACHE and GO_PACKAGE_PATH directories
  openshift-ci/Dockerfile.tests
Labels: size/XS

#23 Introduce helm user to run the tests as non-root.
  openshift-ci/Dockerfile.tests
Labels: size/S

#24 Update root image for OpenShift CI.
  openshift-ci/Dockerfile.tests
Labels: size/M

#25 Parametrize go version in root image.
  openshift-ci/Dockerfile.tests
Labels: size/XS

#26 Remove use of GOROOT env variable in root image for OpenShift CI.
  openshift-ci/Dockerfile.tests
Labels: size/S

#27 Update Dockerfile for OpenShift CI to work with unit tests.
  openshift-ci/Dockerfile.tests
Labels: size/XS

#13 Repair failing unit tests - failure caused by io.Stat return values for directory size
  pkg/chartutil/expand_test.go
Labels: size/M

#9 Introduce openshift-ci/Makefile to be used on OpenShift CI
  openshift-ci/Makefile
Labels: size/S

#34 Set GOCACHE and XDG_CACHE_HOME for OpenShift CI.
  openshift-ci/.gitignore
  openshift-ci/Makefile
Labels: size/S

#35 V3.0 unit test fix
  .circleci/bootstrap.sh
  .circleci/config.yml
  Makefile
  cmd/helm/installer/init.go
  cmd/helm/installer/init_test.go
  cmd/helm/repo_remove_test.go
  cmd/helm/testdata/output/version-client-shorthand.txt
  cmd/helm/testdata/output/version-client.txt
  cmd/helm/testdata/output/version-short.txt
  cmd/helm/testdata/output/version-template.txt
  cmd/helm/testdata/output/version.txt
  go.mod
  go.sum
  internal/third_party/dep/fs/fs_test.go
  internal/tlsutil/tls.go
  internal/tlsutil/tlsutil_test.go
  internal/version/version.go
  pkg/action/show_test.go
  pkg/chartutil/capabilities_test.go
  pkg/chartutil/capabilities_versions_generated.go
  pkg/cli/environment_test.go
  pkg/downloader/manager.go
  pkg/downloader/manager_test.go
  pkg/getter/httpgetter.go
  pkg/getter/httpgetter_test.go
  pkg/lint/rules/chartfile.go
  pkg/releaseutil/sorter.go
  pkg/storage/storage_test.go
  pkg/strvals/parser.go
  pkg/strvals/parser_test.go
Labels: ok-to-test, size/XXL
