Repository redhat-developer/helm, pull requests merged in 2020-03, with the labels that each got.

#46 Acceptance tests poc
  openshift-ci/Dockerfile.tests
  openshift-ci/Makefile.acceptance
Labels: size/M

#47 Update the openshift-ci/Makefile to make the Makefile.acceptance obsolete
  openshift-ci/Dockerfile.tests
  openshift-ci/Makefile
Labels: size/XS

#48 [WIP] Remove obsolete openshift-ci/Makefile.acceptance file
  openshift-ci/Dockerfile.tests
  openshift-ci/Makefile.acceptance
Labels: do-not-merge/work-in-progress, size/M

#52 OWNERS housekeeping
  OWNERS
Labels: approved, lgtm
