Repository redhat-developer/helm, pull requests merged in 2020-02, with the labels that each got.

#37 Enable ppc64le and s390x binaries
  Makefile
  pkg/plugin/plugin_test.go
Labels: ok-to-test, size/S

#40 Set the version of golangci-lint binary to the same as in upstream.
  openshift-ci/Makefile
Labels: size/XS

#39 Updated OWNERS to the internal ones
  OWNERS
Labels: lgtm, size/M

#41 Sync go version with upstream CI (1.13.8) and change ubi base image to v8.
  openshift-ci/Dockerfile.tests
Labels: lgtm, size/XS

#43 Fix OpenShift CI base image registry.
  openshift-ci/Dockerfile.tests
Labels: size/XS
